### ISSUE TITLE
Suggestion: add Custom Windows Size option

### ISSUE THREAD

**Issue by pcwizard7** [ryanrudolfoba/SteamOS-installer-dualboot-wizard#1]
I like the option to be able to enter a custom GB size for windows and then allocate the rest to SteamOS.

Thanks

**Comment by ryanrudolfoba** [comment]
For now it will be essier for me to write the script and ask the end user for SteamOS size, and then the remaining will be for Windows.

If i do the reverse, ask size for Windows and then the rest for SteamOS - the calculation can get messy. I'll see what i can do.

**Comment by pcwizard7** [comment]
> For now it will be essier for me to write the script and ask the end user for SteamOS size, and then the remaining will be for Windows.
> 
> If i do the reverse, ask size for Windows and then the rest for SteamOS - the calculation can get messy. I'll see what i can do.

if you could asked the user for a custom size for SteamOS would be another option too

**Comment by ryanrudolfoba** [comment]
updated script it now has the option for CUSTOM partitioning.

![image](https://user-images.githubusercontent.com/98122529/219874357-fddf841d-51c2-48f6-95a5-4ddcd1c53e32.png)

![image](https://user-images.githubusercontent.com/98122529/219874434-b80ac205-fa94-4e09-84c6-2162edf4d976.png)

**Comment by ryanrudolfoba** [comment]
updated script it now has the option for CUSTOM partitioning.
