### ISSUE TITLE
Suggestion: Link to jlobue10's rEFInd setup / guide.

### ISSUE THREAD

**Issue by Kazlehoff** [ryanrudolfoba/SteamOS-installer-dualboot-wizard#2]
https://github.com/jlobue10/SteamDeck_rEFInd

comes with a GUI and further information to setting up windows properly for dual boot.

**Comment by ryanrudolfoba** [comment]
sorry for the late reply. I have my own dual boot script implementation using clover -

https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot
