### ISSUE TITLE
stuck and doesnt go further

### ISSUE THREAD

**Issue by TwisstedToast** [ryanrudolfoba/SteamOS-installer-dualboot-wizard#3]
I have saw that it doesn't go further than 
+ 'steamos-chroot' '--disk' '/dev/nvm0n1' '--partset' 'A' '--' 'mkdir' '/efi/SteamOS'
i have tried retrying install, it gets stuck on the same thing
pls help i wanna dualboot windows

**Comment by GuestSneezeOSDev** [comment]
try this https://github.com/LukeShortCloud/winesapOS and dualboot https://github.com/GuestSneezeOSDev/WinesapDualboot

**Comment by ryanrudolfoba** [comment]
> I have saw that it doesn't go further than
> 
> * 'steamos-chroot' '--disk' '/dev/nvm0n1' '--partset' 'A' '--' 'mkdir' '/efi/SteamOS'
>   i have tried retrying install, it gets stuck on the same thing
>   pls help i wanna dualboot windows

Sorry for late reply. The script is based on SteamOS 3.4, most probably need to update the script to work with the latest SteamOS recovery image based on SteamOS 3.5.

I haven't looked into this yet but I plan to update things once the schedule gets a free time.

**Comment by GuestSneezeOSDev** [comment]
you could build it
